# Generated by Django 5.2.6 on 2025-09-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFilmSay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='MyFilmSay.commentreply'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='MyFilmSay.comment'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_user_comment_vote'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'reply'), name='unique_user_reply_vote'),
        ),
    ]
